# Generated by Django 3.1 on 2021-01-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_auto_20210123_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsToDelivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductPackaged', models.BooleanField(default=False)),
                ('ProductShipeed', models.BooleanField(default=False)),
                ('ProductDilivered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
