# Generated by Django 3.1 on 2021-01-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210123_2320'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsToDelivered',
            new_name='ProductsToDeliver',
        ),
    ]
