# Generated by Django 3.1 on 2021-01-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_users', '0006_auto_20210129_2130'),
        ('seller', '0005_auto_20210129_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstodeliver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_users.buyer'),
        ),
    ]
