# Generated by Django 3.1 on 2021-02-17 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210129_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstodeliver',
            name='ProductDEliverDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
