# Generated by Django 3.1 on 2021-02-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_productstodeliver_productdeliverdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstodeliver',
            old_name='ProductDEliverDate',
            new_name='ProductDeliveryDate',
        ),
    ]
