# Generated by Django 3.1 on 2021-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20210217_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstodeliver',
            name='ProductDeliveryDate',
            field=models.DateField(),
        ),
    ]
