# Generated by Django 3.1 on 2021-02-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_users', '0007_buyer_phone'),
        ('home', '0016_auto_20210129_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_users.buyer')),
            ],
        ),
    ]
