# Generated by Django 3.1.5 on 2021-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricture',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
    ]
