# Generated by Django 3.1 on 2021-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_pricture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricture',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
