# Generated by Django 3.1 on 2021-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210123_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='announcement_type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Toys', 'Toys'), ('Clothing', 'Clothing')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
