# Generated by Django 3.1 on 2021-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210123_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Toys', 'Toys'), ('Clothing', 'Clothing'), ('Vehicle', 'Vehicle')], max_length=50),
        ),
    ]
