# Generated by Django 3.1 on 2021-01-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_images',
            new_name='ProductImages',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='pricture',
            new_name='product',
        ),
    ]
