# Generated by Django 3.1 on 2021-01-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210123_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pricture',
            new_name='thumbnail',
        ),
    ]
